/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import gameManager from "./game/gameManager"
import hammer from "./game/hammer"
import mouse from "./game/mouse"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=960;
    static height:number=640;
    static scaleMode:string="fixedauto";
    static screenMode:string="horizontal";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="ceshi.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("game/gameManager.ts",gameManager);
        reg("game/hammer.ts",hammer);
        reg("game/mouse.ts",mouse);
    }
}
GameConfig.init();